sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
notifications:
    email: false
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export C_INCLUDE_PATH="$HOME/miniconda/include:$C_INCLUDE_PATH"
  - export CPLUS_INCLUDE_PATH="$HOME/miniconda/include:$CPLUS_INCLUDE_PATH"
  - conda update --yes conda
  - conda config --add channels conda-forge
install:
  - conda install --yes gsl
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib cython nose
  - pip install -v -e .
script: nosetests test
